version: "2"

run:
  relative-path-mode: gomod
  concurrency: 8
  issues-exit-code: 1
  tests: true

linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - copyloopvar
    - cyclop
    - decorder
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - inamedparam
    - ineffassign
    - interfacebloat
    - lll
    - loggercheck
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    revive:
      confidence: 0.1
      rules:
        - name: exported
          disabled: true
    stylecheck:
      # I like ST1003, but many people may disagree.
      checks: ["all", "-ST1020", "-ST1021", "-ST1000", "-ST1003"]
    interfacebloat:
      max: 3
    errcheck:
      check-type-assertions: true
      check-blank: true
    testifylint:
      enable-all: true
    govet:
      enable-all: true
    funlen:
      ignore-comments: true
    nolintlint:
      allow-unused: false
      allow-no-explanation: []
      require-explanation: true
      require-specific: true
    gocognit:
      min-complexity: 15
    gocyclo:
      min-complexity: 15
    gocritic:
      enable-all: true
    nakedret:
      max-func-lines: 0
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - bodyclose
          - dupl
          - funlen
          - gochecknoglobals
          - goconst
          - gosec
          - noctx
          - wrapcheck
        path: _test\.go
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Rollback). is not checked
      - path: (.+)\.go$
        text: should check returned error before deferring
    paths:
      - bin
      - builtin$
      - examples$
      - third_party$
      - tmp
      - var
      - vendor
  issues:
  max-same-issues: 50

formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - bin
      - builtin$
      - examples$
      - tmp
      - var
      - vendor
